version: '3'
services:

  unittest:
    container_name: 'unittest'
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "pipenv run test_dynamodb && pipenv run test_lambdalib"
    environment:
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy
      AWS_REGION: us-east-1
      AWS_DEFAULT_REGION: us-east-1
    volumes:
      - ./:/usr/src/app
    depends_on:
      - dynamodb
    networks:
      - back-tier

  # dynamodb docker container
  dynamodb:
    image: amazon/dynamodb-local
    container_name: local_dynamodb
    volumes:
      # host : container
      - "./local/dynamodb:/data"
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -port 8000 -sharedDb -dbPath /data"
    networks:
      - back-tier
      - dynamodb-tier

  # dynamodb admin docker container
  dynamodb-admin:
    image: aaronshaf/dynamodb-admin:latest
    container_name: local_dynamodb-admin
    environment:
      - DYNAMO_ENDPOINT=dynamodb:8000
    ports:
      - 8001:8001
    depends_on:
      - dynamodb
    networks:
      - dynamodb-tier

# network
networks:
  back-tier:
  dynamodb-tier:
    driver: bridge
